---
title: "ggplot2 demo"
author: "Ylo Maivali"
date: "20 September 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the qiz dataset
```{r}
library(tidyverse)
library(ggthemes)

a <- read_csv("data/quiz.csv")

colnames(a) <- c("subject", "years", "supervisor", 
                 "stat_course", "data_anal", "R_prof",
                 "x", "x1", "x2", "x3", "x4", "x5", "x6")
a <- select(a, -x)

a <- mutate(a, diff_x1_x2=x1 - x2)

a$years <- parse_number(a$years)
a
```

First some simple plots with base graphics. The main function is plot().
```{r}
barplot(table(a$data_anal))
```

```{r}
plot(a$x1)
```

```{r}
a$supervisor <- as.factor(a$supervisor)
# a$supervisor <- as.character(a$supervisor)
plot(a$supervisor, a$x1, xlim=c(-10,10))
boxplot(a$x1~a$supervisor)
#inline comment
```

```{r}
stripchart(a$x4)
```

```{r}
hist(a$x1, breaks=10)
```

```{r}
plot(a$x3, a$x4)
abline(lm(a$x3~a$x4))
```

```{r}
hist(a$x5, breaks = 5)
```

```{r}

```

# ggplot2

```{r}
iris <- iris
iris <- as_tibble(iris)
str(iris)
```

ggplot
```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species))+
  geom_point()+
  geom_smooth(method = "lm", se=FALSE, color="red")+
  theme_tufte()
```

```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point()+
  geom_smooth(data=filter(iris, Species %in% c("virginica", "versicolor")), method="lm")+
  theme_bw()
```

```{r}
iris1 <- iris %>% filter(Species=="setosa")

ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species)+
  geom_point()+
  geom_smooth(data=iris1, method="lm")
```

```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species))+
  geom_point()+
  geom_smooth(method="lm")
```

```{r}
(midwest <- as_tibble(midwest) %>% select(percwhite, percbelowpoverty, poptotal))
```

```{r}
ggplot(midwest, aes(percwhite, percbelowpoverty))+
  geom_point(aes(size=poptotal))+
  geom_smooth(aes(weigth= poptotal), method=lm, size=1)+
  geom_smooth(method = lm, color="red")
```

